CREATE TABLE CATEGORY(

ID IDENTITY,
NAME VARCHAR(50),
DESCRIPTION  VARCHAR(255),
IMAGE_URL VARCHAR(50),
IS_ACTIVE BOOLEAN,

CONSTRAINT PK_CATEGORY_ID PRIMARY KEY(ID)

);

DROP TABLE CATEGORY


INSERT INTO CATEGORY (NAME,DESCRIPTION,IMAGE_URL,IS_ACTIVE) VALUES ('Flowers','Flowers brings colors and happiness into everyone`s lives','Flowers.png','TRUE')


INSERT INTO CATEGORY (NAME,DESCRIPTION,IMAGE_URL,IS_ACTIVE) VALUES ('Pets','Pets are good companions to humans','Pets.png','TRUE');

SELECT * FROM CATEGORY;

CREATE TABLE USER_DETAIL(

	ID IDENTITY,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	ROLE VARCHAR(50),
	ENABLED BOOLEAN,
	PASSWORD VARCHAR(50),
	EMAIL VARCHAR(100),
	CONTACT_NUMBER VARCHAR(15),
	CONSTRAINT PK_USER_ID PRIMARY KEY(ID)

);


INSERT INTO USER_DETAIL(FIRST_NAME,LAST_NAME,ROLE,ENABLED,PASSWORD,EMAIL,CONTACT_NUMBER) VALUES('Priyanka','Ketireddi','ADMIN',true,'admin','pk@gmail.com','5555555555');

INSERT INTO USER_DETAIL(FIRST_NAME,LAST_NAME,ROLE,ENABLED,PASSWORD,EMAIL,CONTACT_NUMBER) VALUES('Amie','Anderson','ADMIN',true,'admin','aa@gmail.com','9999999999');

INSERT INTO USER_DETAIL(FIRST_NAME,LAST_NAME,ROLE,ENABLED,PASSWORD,EMAIL,CONTACT_NUMBER) VALUES('Jackie','Chan','ADMIN',true,'admin','jc@gmail.com','7777777777');


CREATE TABLE PRODUCT(
	ID IDENTITY,
	CODE VARCHAR(20),
	NAME VARCHAR(50),
	BRAND VARCHAR(50),
	DESCRIPTION VARCHAR(255),
	UNIT_PRICE DECIMAL(10,2),
	QUANTITY INT,
	IS_ACTIVE BOOLEAN,
	CATEGORY_ID INT,
	SUPPLIER_ID INT,
	PURCHASES INT DEFAULT 0,
	VIEWS INT DEFAULT 0,
	CONSTRAINT PK_PRODUCT_ID PRIMARY KEY(ID),
	CONSTRAINT FK_PRODUCT_CATEGORY_ID FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID),
	CONSTRAINT FK_PRODUCT_SUPPLIER_ID FOREIGN KEY(SUPPLIER_ID) REFERENCES USER_DETAIL(ID)
);


INSERT INTO PRODUCT(CODE,NAME,BRAND,DESCRIPTION,UNIT_PRICE,QUANTITY,IS_ACTIVE,CATEGORY_ID,SUPPLIER_ID) 
VALUES('1566792','Roses','Love','Roses are symbol of love',200,1,true,1,1);


INSERT INTO PRODUCT(CODE,NAME,BRAND,DESCRIPTION,UNIT_PRICE,QUANTITY,IS_ACTIVE,CATEGORY_ID,SUPPLIER_ID) 
VALUES('3441597','Jasmine','Peace','Jasmine gives excellent fragrance',190,1,true,1,2);

INSERT INTO PRODUCT(CODE,NAME,BRAND,DESCRIPTION,UNIT_PRICE,QUANTITY,IS_ACTIVE,CATEGORY_ID,SUPPLIER_ID) 
VALUES('2536194','Lotus','Beauty','Pink Lotus flowers are beautiful',260,1,true,1,3);

INSERT INTO PRODUCT(CODE,NAME,BRAND,DESCRIPTION,UNIT_PRICE,QUANTITY,IS_ACTIVE,CATEGORY_ID,SUPPLIER_ID) 
VALUES('6823823287','Orange Roses','Love','Roses are symbol of love',210,1,true,1,1);



INSERT INTO PRODUCT(CODE,NAME,BRAND,DESCRIPTION,UNIT_PRICE,QUANTITY,IS_ACTIVE,CATEGORY_ID,SUPPLIER_ID) 
VALUES('16408319482','Green Parrot','Love','Green parrots eat fruits and are loved by people',210,1,true,2,2);


INSERT INTO PRODUCT(CODE,NAME,BRAND,DESCRIPTION,UNIT_PRICE,QUANTITY,IS_ACTIVE,CATEGORY_ID,SUPPLIER_ID) 
VALUES('2107052','Swan','Love','Swan are white in color and they live in water',210,1,true,2,3);



INSERT INTO PRODUCT(CODE,NAME,BRAND,DESCRIPTION,UNIT_PRICE,QUANTITY,IS_ACTIVE,CATEGORY_ID,SUPPLIER_ID) 
VALUES('5819482445','Peacock','Beauty','Peacocks are known for its dance and its colorful feathers',210,1,true,2,1);


INSERT INTO PRODUCT(CODE,NAME,BRAND,DESCRIPTION,UNIT_PRICE,QUANTITY,IS_ACTIVE,CATEGORY_ID,SUPPLIER_ID) 
VALUES('4513823526','fish','Beauty','water is homeland for fish ',210,1,true,2,2);

SELECT * FROM CATEGORY;

SELECT * FROM USER_DETAILS

SELECT * FROM PRODUCT;

DROP TABLE PRODUCT

